<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.application</groupId>
        <artifactId>customer</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>view</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>24</java.version>
        <javafx.version>24.0.1</javafx.version>
        <javafx.sdk>C:/PC/Application/JAVA-APLICATIONS/javafx-sdk-21.0.2</javafx.sdk>
    </properties>
    <dependencies>
        <!--
                java &#45;&#45;module-path "C:/PC/Application/JAVA-APLICATIONS/javafx-sdk-21.0.2/lib" &#45;&#45;add-modules javafx.controls,javafx.fxml -jar application.jar
        -->

        <dependency>
            <groupId>org.application</groupId>
            <artifactId>service</artifactId>
            <version>${project.version}</version>
        </dependency>


        <!-- for native image -->
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>24.0.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>native-image-maven-plugin</artifactId>
            <version>21.2.0</version>
        </dependency>

        <!--        <dependency>
                    <groupId>org.graalvm.nativeimage</groupId>
                    <artifactId>svm</artifactId>
                    <version>22.3.0</version>
                    <scope>provided</scope>
                </dependency>-->

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
            <classifier>win</classifier>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
            <classifier>win</classifier>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>${javafx.version}</version>
            <classifier>win</classifier>
        </dependency>


    </dependencies>
    <build>
        <plugins>
            <!--
                         java &#45;&#45;module-path "C:/PC/Application/JAVA-APLICATIONS/javafx-sdk-21.0.2/lib" &#45;&#45;add-modules javafx.controls,javafx.fxml -jar application-1.0-SNAPSHOT-shaded.jar
-->

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.application.desktop.MainApp</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>

                        <manifest> <!--نام کامل پکیج به همراه نام کلاس ک ه متد main در آن موجود است -->
                            <Main-Class>org.application.desktop.MainApp</Main-Class>
                            <addClasspath>true</addClasspath>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>


            <!-- mvn javafx:run -->

            <!-- افزونه JavaFX برای اجرا -->

            <!-- mvn exec:exec -->  <!-- debug -->
            <!-- mvn exec:java -->  <!-- run -->

            <!-- netstat -an | find "5005" -->
            <!-- netstat -voa | find "5005" -->
            <!-- taskkill /PID 9304 /F -->


        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.properties</include>
                    <include>**/*.json</include>
                    <include>**/*.sql</include>
                </includes>
                <excludes>
                    <exclude>help/**</exclude>
                </excludes>
                <filtering>false</filtering>
            </resource>
        </resources>

        <!-- jar tf target/view.jar | grep MainApp -->  <!-- linux -->
        <!-- jar tf target/view.jar | findstr MainApp -->  <!-- windows -->
        <!-- jar tf target/view.jar | findstr CustomerService -->
        <!-- java -jar application.jar -->
        <finalName>${artifactId}</finalName>
    </build>


    <!--  mvn clean install -Pnative-image -->
    <!--  mvn clean install -Pnative-image -->

    <profiles>
        <profile>
            <id>run</id>
            <properties>

            </properties>
            <activation> <!-- for run application -->
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>build</name>
                    <value>develop</value>
                </property>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <version>0.0.8</version>
                        <configuration>
                            <mainClass>org.application.desktop.MainApp</mainClass>
                            <options>
                                <option>-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005</option>
                            </options>
                        </configuration>
                        <executions>
                            <execution>
                                <id>create-reflection-config</id>
                                <phase>process-classes</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>build</id>
            <properties>

            </properties>
            <activation> <!-- for build application -->
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>build</name>
                    <value>build</value>
                </property>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <version>0.0.8</version>
                        <configuration>
                            <mainClass>org.application.desktop.MainApp</mainClass>
                            <options>
                                <option>-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005</option>
                            </options>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>


        <profile>
            <id>native-image</id>
            <properties>

            </properties>
            <activation> <!-- for create native image -->
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>build</name>
                    <value>release</value>
                </property>
            </activation>


            <build>

                <plugins>

                    <!-- GraalVM Native Image Plugin -->

                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.10.6</version>
                        <configuration>
                            <imageName>application</imageName>
                            <mainClass>org.application.desktop.MainApp</mainClass>
                            <buildArgs>


                                <buildArg>--initialize-at-build-time=com.sun.javafx.logging.PlatformLogger</buildArg>
                                <buildArg>--initialize-at-build-time=javafx.css</buildArg>
                                <buildArg>--initialize-at-build-time=com.sun.javafx.css</buildArg>
                                <buildArg>-H:IncludeResources=.*\\.css</buildArg>
                                <buildArg>-H:IncludeResources=.*\\.bss</buildArg>

                                <buildArg>--initialize-at-build-time=com.sun.scenario.animation.SplineInterpolator</buildArg>
                                <buildArg>--initialize-at-build-time=com.sun.scenario.animation.StepInterpolator</buildArg>


                                <buildArg>--verbose</buildArg>
                                <buildArg>--diagnostics-mode</buildArg>

                                <buildArg>--initialize-at-run-time=io.netty</buildArg>
                                <buildArg>--initialize-at-run-time=org.slf4j</buildArg>

                                <!-- add memory-->
                                <buildArg>-J-Xmx8G</buildArg>
                                <!--<buildArg>&#45;&#45;no-fallback</buildArg>-->
                                <buildArg>--enable-url-protocols=http,https</buildArg>
                                <buildArg>--enable-native-access=ALL-UNNAMED</buildArg>

                                <buildArg>-H:+ReportExceptionStackTraces</buildArg>

                                <!--<buildArg>-H:+TraceClassInitialization</buildArg>-->
                                <buildArg>-H:+PrintClassInitialization</buildArg>
                                <buildArg>--no-fallback</buildArg>

                                <buildArg>-H:+AddAllCharsets</buildArg>
                                <buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
                                <buildArg>-H:ConfigurationFileDirectories=${project.basedir}/src/main/resources/config</buildArg>


                                <buildArg>--initialize-at-run-time=javafx.scene.control.PopupControl</buildArg>
                                <buildArg>--initialize-at-run-time=javafx.scene</buildArg>
                                <buildArg>--initialize-at-run-time=javafx.scene.control</buildArg>

                                <buildArg>--initialize-at-build-time=javafx.scene.image.Image$1</buildArg>
                                <buildArg>--initialize-at-build-time=javafx.scene.input.KeyCodeCombination</buildArg>
                                <buildArg>--initialize-at-build-time=javafx.scene.input.KeyCombination$Modifier</buildArg>
                                <buildArg>--initialize-at-build-time=javafx.scene.input.KeyCode</buildArg>
                                <buildArg>--initialize-at-build-time=javafx.scene.input.KeyCombination$ModifierValue</buildArg>
                                <buildArg>--initialize-at-build-time=javafx.scene.input.KeyCombination$1</buildArg>

                                <!-- برای حل مشکل thread در JavaFX -->
                                <buildArg>--initialize-at-run-time=javafx.stage.Screen</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.glass.ui.Application</buildArg>


                                <buildArg>--initialize-at-run-time=com.sun.javafx.tk.quantum.QuantumToolkit</buildArg>

                                <buildArg>--initialize-at-run-time=javafx.stage</buildArg>
                                <buildArg>--initialize-at-run-time=javafx.graphics</buildArg>


                                <buildArg>--initialize-at-run-time=javafx.scene.control.PopupControl$1</buildArg>
                                <buildArg>--initialize-at-run-time=javafx.scene.control.PopupControl$2</buildArg>

                                <buildArg>--initialize-at-build-time=javafx.graphics,javafx.controls,javafx.base,javafx.fxml</buildArg>


                                <buildArg>--initialize-at-build-time=javafx.application.Platform</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.prism.sw.SWPipeline</buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.prism.sw=ALL-UNNAMED</buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.javafx.tk.quantum=ALL-UNNAMED</buildArg>


                                <buildArg>--initialize-at-build-time=org.application.desktop.MainApp</buildArg>
                                <buildArg>--initialize-at-build-time=javafx.application.Application</buildArg>
                                <buildArg>--initialize-at-build-time=com.sun.javafx.application.PlatformImpl</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.glass.ui</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.javafx.tk.quantum</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.prism.d3d.D3DPipeline</buildArg>
                                <buildArg>--initialize-at-run-time=org.mariadb.jdbc.Driver</buildArg>


                                <buildArg>
                                    --initialize-at-build-time=javafx.beans.property.SimpleBooleanProperty,javafx.beans.property,javafx.beans
                                </buildArg>

                                <buildArg>--trace-object-instantiation=java.lang.Thread</buildArg>
                                <buildArg>--report-unsupported-elements-at-runtime</buildArg>


                                <buildArg>--trace-object-instantiation=java.lang.Thread</buildArg>

                                <!-- تنظیمات گرافیک -->
                                <buildArg>-Dprism.order=sw,d3d</buildArg>
                                <buildArg>-H:IncludeResources=com/sun/prism/d3d/.*</buildArg>
                                <buildArg>-H:IncludeResources=com/sun/prism/es2/.*</buildArg>

                                <buildArg>-Djava.awt.headless=true</buildArg>
                                <buildArg>-Dprism.verbose=true</buildArg>
                                <buildArg>--allow-incomplete-classpath</buildArg>

                                <buildArg>--initialize-at-build-time=com.sun.glass.ui</buildArg>
                                <buildArg>--initialize-at-build-time=com.sun.javafx.tk</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.javafx.tk.quantum.QuantumRenderer</buildArg>

                                <buildArg>-H:IncludeResources=com/sun/javafx/font/.*</buildArg>
                                <buildArg>-H:IncludeResources=com/sun/prism/.*</buildArg>
                                <buildArg>-H:IncludeResources=com/sun/javafx/.*</buildArg>
                                <buildArg>-H:IncludeResourceBundles=com.sun.prism</buildArg>
                                <buildArg>-H:IncludeResourceBundles=com.sun.prism.resources.prism</buildArg>

                                <buildArg>--initialize-at-build-time=com.sun.prism.sw</buildArg>
                                <buildArg>--initialize-at-build-time=com.sun.javafx.tk.quantum</buildArg>

                                <buildArg>--initialize-at-build-time=javafx</buildArg>
                                <buildArg>-H:IncludeResources=.*fxml$</buildArg>
                                <buildArg>-H:IncludeResources=.*css$</buildArg>
                                <buildArg>-H:IncludeResources=.*png$</buildArg>


                                <buildArg>-H:IncludeResourceBundles=com.sun.javafx.tk.quantum.QuantumMessagesBundle
                                </buildArg>



                            </buildArgs>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                    </plugin>


                    <!--                    <plugin>
                                            <groupId>org.codehaus.mojo</groupId>
                                            <artifactId>exec-maven-plugin</artifactId>
                                            <version>3.1.0</version>
                                            <executions>
                                                <execution>
                                                    <id>set-exe-icon</id>
                                                    <phase>package</phase>
                                                    <goals>
                                                        <goal>exec</goal>
                                                    </goals>
                                                    <configuration>
                                                        <executable>rcedit</executable>
                                                        <arguments>
                                                            <argument>${project.build.directory}/application.exe</argument>
                                                            <argument>&#45;&#45;set-icon</argument>
                                                            <argument>
                                                                ${project.basedir}/src/main/resources/icon/tropical_vacation_iconset.png
                                                            </argument>
                                                        </arguments>
                                                    </configuration>
                                                </execution>
                                            </executions>
                                        </plugin>-->

                </plugins>

            </build>
        </profile>

    </profiles>


    <repositories>
        <repository>
            <id>maven</id>
            <name>Maven-Central-Repository</name>
            <url>https://mvnrepository.com/artifact</url>
        </repository>

        <repository>
            <id>central</id>
            <name>Maven Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>

        <repository>
            <id>openjfx</id>
            <url>https://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
        </repository>
    </repositories>

</project>