<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.application</groupId>
        <artifactId>customer</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>view</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>24</java.version>
        <javafx.version>21</javafx.version>
        <javafx.sdk>C:/PC/Application/JAVA-APLICATIONS/javafx-sdk-21.0.2</javafx.sdk>
    </properties>
    <dependencies>
        <!--
                java &#45;&#45;module-path "C:/PC/Application/JAVA-APLICATIONS/javafx-sdk-21.0.2/lib" &#45;&#45;add-modules javafx.controls,javafx.fxml -jar application.jar
        -->

        <dependency>
            <groupId>org.application</groupId>
            <artifactId>service</artifactId>
            <version>${project.version}</version>
        </dependency>


        <!-- for native image -->
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>24.0.1</version>
            <scope>provided</scope>
        </dependency>

<!--        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>native-image-maven-plugin</artifactId>
            <version>21.2.0</version>
        </dependency>-->

        <!--        <dependency>
                    <groupId>org.graalvm.nativeimage</groupId>
                    <artifactId>svm</artifactId>
                    <version>22.3.0</version>
                    <scope>provided</scope>
                </dependency>-->

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
            <classifier>win</classifier>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
            <classifier>win</classifier>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>${javafx.version}</version>
            <classifier>win</classifier>
        </dependency>


        <dependency>
            <groupId>com.gluonhq</groupId>
            <artifactId>charm-glisten</artifactId>
            <version>6.2.3</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <!--
                         java &#45;&#45;module-path "C:/PC/Application/JAVA-APLICATIONS/javafx-sdk-21.0.2/lib" &#45;&#45;add-modules javafx.controls,javafx.fxml -jar application-1.0-SNAPSHOT-shaded.jar
-->

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.application.desktop.MainApp</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>

                        <manifest> <!--نام کامل پکیج به همراه نام کلاس ک ه متد main در آن موجود است -->
                            <Main-Class>org.application.desktop.MainApp</Main-Class>
                            <addClasspath>true</addClasspath>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <id>run-with-agent</id>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>org.application.desktop.MainApp</mainClass>
                    <arguments></arguments>
                    <systemProperties>
                        <systemProperty>
                            <key>java.library.path</key>
                            <value>${env.JAVA_HOME}/lib</value>
                        </systemProperty>
                    </systemProperties>
                    <commandlineArgs>
                        -agentlib:native-image-agent=config-merge-dir=src/main/resources/config1
                    </commandlineArgs>
                </configuration>
            </plugin>




            <!-- mvn javafx:run -->

            <!-- افزونه JavaFX برای اجرا -->

            <!-- mvn exec:exec -->  <!-- debug -->
            <!-- mvn exec:java -->  <!-- run -->

            <!-- netstat -an | find "5005" -->
            <!-- netstat -voa | find "5005" -->
            <!-- taskkill /PID 9304 /F -->


        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.properties</include>
                    <include>**/*.json</include>
                    <include>**/*.sql</include>
                </includes>
                <excludes>
                    <exclude>help/**</exclude>
                </excludes>
                <filtering>false</filtering>
            </resource>
        </resources>

        <!-- jar tf target/view.jar | grep MainApp -->  <!-- linux -->
        <!-- jar tf target/view.jar | findstr MainApp -->  <!-- windows -->
        <!-- jar tf target/view.jar | findstr CustomerService -->
        <!-- java -jar application.jar -->
        <finalName>${artifactId}</finalName>
    </build>


    <!--  mvn clean install -Pnative-image -->
    <!--  mvn clean install -Pnative-image -->

    <profiles>
        <profile>
            <id>run</id>
            <properties>

            </properties>
            <activation> <!-- for run application -->
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>build</name>
                    <value>develop</value>
                </property>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <version>0.0.8</version>
                        <configuration>
                            <mainClass>org.application.desktop.MainApp</mainClass>
                            <options>
                                <option>-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005</option>
                            </options>
                        </configuration>
                        <executions>
                            <execution>
                                <id>create-reflection-config</id>
                                <phase>process-classes</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>build</id>
            <properties>

            </properties>
            <activation> <!-- for build application -->
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>build</name>
                    <value>build</value>
                </property>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <version>0.0.8</version>
                        <configuration>
                            <mainClass>org.application.desktop.MainApp</mainClass>
                            <options>
                                <option>-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005</option>
                            </options>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>


        <profile>
            <id>native-image</id>
            <properties>

            </properties>
            <activation> <!-- for create native image -->
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>build</name>
                    <value>release</value>
                </property>
            </activation>


            <build>

                <plugins>

                    <!-- GraalVM Native Image Plugin -->


                    <!--
# ساخت برنامه با Maven
                    mvn clean package -Pnative-image

                    # ساخت native image
                    mvn gluonfx:build -Pnative-image

# ایجاد بسته نهایی (EXE)
                    mvn gluonfx:package -Pnative-image


                    -->

                    <plugin>
                        <groupId>com.gluonhq</groupId>
                        <artifactId>gluonfx-maven-plugin</artifactId>
                        <version>1.0.27</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>compile</goal>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>org.application.desktop.MainApp</mainClass>

                            <nativeImageArgs>
                                <arg>--verbose</arg>
                                <arg>-H:+ReportExceptionStackTraces</arg>
                                <arg>--allow-incomplete-classpath</arg>
                                <arg>--report-unsupported-elements-at-runtime</arg>
                                <arg>-H:+AddAllCharsets</arg>
                                <arg>-H:EnableURLProtocols=http,https</arg>
                                <arg>-Dprism.verbose=true</arg>
                                <arg>-Djavafx.verbose=true</arg>
                                <arg>--enable-url-protocols=http,https</arg>

                                <!-- تنظیمات جدید اضافه شده -->
                                <arg>--no-fallback</arg>
                                <!--<arg>-H:+TraceClassInitialization</arg>-->
                                <arg>--initialize-at-run-time=javafx.scene.Node,javafx.scene.Parent,javafx.scene.Scene</arg>
                                <arg>--initialize-at-build-time=org.application,javafx,javafx.graphics,javafx.base</arg>

                                <!-- اگر از FXML استفاده می‌کنید -->
                                <arg>--initialize-at-build-time=javafx.fxml</arg>



                                <!-- تنظیمات جدید برای JavaFX -->
                                <arg>--initialize-at-build-time=javafx.graphics</arg>
                                <arg>-H:+AllowIncompleteClasspath</arg>


                                <arg>--initialize-at-run-time=javafx.scene.CssStyleHelper</arg>
                                <arg>--initialize-at-run-time=com.sun.javafx.css.StyleManager</arg>
                                <arg>--initialize-at-run-time=javafx.scene.text.Font</arg>
                                <arg>--initialize-at-run-time=javafx.scene.Parent</arg>
                                <arg>--initialize-at-run-time=javafx.scene.Node</arg>
                                <arg>--initialize-at-run-time=javafx.scene.Scene</arg>
                                <arg>--initialize-at-run-time=com.sun.javafx.tk.quantum.QuantumRenderer</arg>
                                <arg>--initialize-at-run-time=com.sun.prism.d3d.D3DPipeline</arg>
                                <arg>--initialize-at-run-time=com.sun.prism.sw.SWPipeline</arg>



                                <arg>--initialize-at-build-time=javafx</arg>

                                <arg>--enable-url-protocols=http,https</arg>


                                <arg>-H:IncludeResources=.*\.fxml$</arg>
                                <arg>-H:IncludeResources=.*\.css$</arg>

                                <arg>-H:+UnlockExperimentalVMOptions</arg>



                                <arg>--initialize-at-build-time=com.sun.javafx</arg>

                                <arg>-H:CLibraryPath=${env.JAVA_HOME}/bin</arg> <!-- اضافه کردن این خط -->


                               <!-- <buildArg>-H:ConfigurationFileDirectories=${project.basedir}/src/main/resources/config</buildArg>

-->

                                <arg>-H:ConfigurationFileDirectories=${project.basedir}/src/main/resources/config</arg>
                               <!-- <arg>-H:ReflectionConfigurationFiles=${project.basedir}/src/main/resources/config/reflection-config.json</arg>
-->
                                <!--<arg>-H:ReachabilityMetadataFiles=${project.basedir}/src/main/resources/config/reachability-metadata.json
                                </arg>-->

                            </nativeImageArgs>

                            <reflectionList>
                                <list>org.application.desktop.dto.CustomerDTO</list>
                                <list>org.application.desktop.MainApp</list>
                                <list>javafx.scene.Node</list>
                                <list>javafx.scene.Parent</list>
                                <list>javafx.scene.Scene</list>
                                <list>javafx.scene.control.Button</list>
                                <!-- سایر کلاس‌های JavaFX که استفاده می‌کنید -->
                                <list>com.sun.javafx.tk.quantum.QuantumRenderer</list>
                            </reflectionList>

                            <bundlesList>
                                <list>org.application</list>
                                <list>com.sun.javafx.scene.control.skin.resources.controls</list>
                                <list>com.sun.javafx.tk.quantum.QuantumMessagesBundle</list>
                                <list>com/sun/glass/ui/win/themes</list>
                                <list>com/sun/javafx/scene/control/skin/resources/controls</list>
                                <list>com/sun/javafx/scene/control/skin/resources/controls-nt</list>
                            </bundlesList>


                            <graalvmHome>C:\PC\Application\JAVA-APLICATIONS\GraalVM\graalvm-jdk-24.0.1+9.1</graalvmHome>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <version>0.0.8</version>
                        <executions>
                            <execution>
                                <id>default-cli</id>
                                <configuration>
                                    <mainClass>org.application.desktop.MainApp</mainClass>
                                    <launcher>app</launcher>
                                    <jlinkZipName>app</jlinkZipName>
                                    <jlinkImageName>app</jlinkImageName>
                                    <noManPages>true</noManPages>
                                    <stripDebug>true</stripDebug>
                                    <noHeaderFiles>true</noHeaderFiles>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>



                    <!--  <plugin>
                          <groupId>org.graalvm.buildtools</groupId>
                          <artifactId>native-maven-plugin</artifactId>
                          <version>0.10.6</version>
                          <configuration>
                              <imageName>application</imageName>
                              <mainClass>org.application.desktop.MainApp</mainClass>
                              <buildArgs>


                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.javafx.logging.PlatformLogger</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.css</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.javafx.css</buildArg>
                                  <buildArg>-H:IncludeResources=.*\\.css</buildArg>
                                  <buildArg>-H:IncludeResources=.*\\.bss</buildArg>

                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.scenario.animation.SplineInterpolator</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.scenario.animation.StepInterpolator</buildArg>


                                  <buildArg>&#45;&#45;verbose</buildArg>
                                  <buildArg>&#45;&#45;diagnostics-mode</buildArg>

                                  <buildArg>&#45;&#45;initialize-at-run-time=io.netty</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=org.slf4j</buildArg>

                                  &lt;!&ndash; add memory&ndash;&gt;
                                  <buildArg>-J-Xmx8G</buildArg>
                                  &lt;!&ndash;<buildArg>&#45;&#45;no-fallback</buildArg>&ndash;&gt;
                                  <buildArg>&#45;&#45;enable-url-protocols=http,https</buildArg>
                                  <buildArg>&#45;&#45;enable-native-access=ALL-UNNAMED</buildArg>

                                  <buildArg>-H:+ReportExceptionStackTraces</buildArg>

                                  &lt;!&ndash;<buildArg>-H:+TraceClassInitialization</buildArg>&ndash;&gt;
                                  <buildArg>-H:+PrintClassInitialization</buildArg>
                                  <buildArg>&#45;&#45;no-fallback</buildArg>

                                  <buildArg>-H:+AddAllCharsets</buildArg>
                                  <buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
                                  <buildArg>-H:ConfigurationFileDirectories=${project.basedir}/src/main/resources/config</buildArg>


                                  <buildArg>&#45;&#45;initialize-at-run-time=javafx.scene.control.PopupControl</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=javafx.scene</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=javafx.scene.control</buildArg>

                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.scene.image.Image$1</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.scene.input.KeyCodeCombination</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.scene.input.KeyCombination$Modifier</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.scene.input.KeyCode</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.scene.input.KeyCombination$ModifierValue</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.scene.input.KeyCombination$1</buildArg>

                                  &lt;!&ndash; برای حل مشکل thread در JavaFX &ndash;&gt;
                                  <buildArg>&#45;&#45;initialize-at-run-time=javafx.stage.Screen</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=com.sun.glass.ui.Application</buildArg>


                                  <buildArg>&#45;&#45;initialize-at-run-time=com.sun.javafx.tk.quantum.QuantumToolkit</buildArg>

                                  <buildArg>&#45;&#45;initialize-at-run-time=javafx.stage</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=javafx.graphics</buildArg>


                                  <buildArg>&#45;&#45;initialize-at-run-time=javafx.scene.control.PopupControl$1</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=javafx.scene.control.PopupControl$2</buildArg>

                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.graphics,javafx.controls,javafx.base,javafx.fxml</buildArg>


                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.application.Platform</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=com.sun.prism.sw.SWPipeline</buildArg>
                                  &lt;!&ndash; <buildArg>&#45;&#45;add-exports=javafx.graphics/com.sun.prism.sw=ALL-UNNAMED</buildArg>
                                   <buildArg>&#45;&#45;add-exports=javafx.graphics/com.sun.javafx.tk.quantum=ALL-UNNAMED</buildArg>
   &ndash;&gt;


                                  <buildArg>&#45;&#45;initialize-at-build-time=org.application.desktop.MainApp</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx.application.Application</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.javafx.application.PlatformImpl</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=com.sun.glass.ui</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=com.sun.javafx.tk.quantum</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=com.sun.prism.d3d.D3DPipeline</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=org.mariadb.jdbc.Driver</buildArg>


                                  <buildArg>
                                      &#45;&#45;initialize-at-build-time=javafx.beans.property.SimpleBooleanProperty,javafx.beans.property,javafx.beans
                                  </buildArg>

                                  <buildArg>&#45;&#45;trace-object-instantiation=java.lang.Thread</buildArg>
                                  <buildArg>&#45;&#45;report-unsupported-elements-at-runtime</buildArg>


                                  <buildArg>&#45;&#45;trace-object-instantiation=java.lang.Thread</buildArg>

                                  &lt;!&ndash; تنظیمات گرافیک &ndash;&gt;
                                  <buildArg>-Dprism.order=sw,d3d</buildArg>
                                  <buildArg>-H:IncludeResources=com/sun/prism/d3d/.*</buildArg>
                                  <buildArg>-H:IncludeResources=com/sun/prism/es2/.*</buildArg>

                                  <buildArg>-Djava.awt.headless=true</buildArg>
                                  <buildArg>-Dprism.verbose=true</buildArg>
                                  <buildArg>&#45;&#45;allow-incomplete-classpath</buildArg>

                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.glass.ui</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.javafx.tk</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-run-time=com.sun.javafx.tk.quantum.QuantumRenderer</buildArg>

                                  <buildArg>-H:IncludeResources=com/sun/javafx/font/.*</buildArg>
                                  <buildArg>-H:IncludeResources=com/sun/prism/.*</buildArg>
                                  <buildArg>-H:IncludeResources=com/sun/javafx/.*</buildArg>
                                  <buildArg>-H:IncludeResourceBundles=com.sun.prism</buildArg>
                                  <buildArg>-H:IncludeResourceBundles=com.sun.prism.resources.prism</buildArg>

                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.prism.sw</buildArg>
                                  <buildArg>&#45;&#45;initialize-at-build-time=com.sun.javafx.tk.quantum</buildArg>

                                  <buildArg>&#45;&#45;initialize-at-build-time=javafx</buildArg>
                                  <buildArg>-H:IncludeResources=.*fxml$</buildArg>
                                  <buildArg>-H:IncludeResources=.*css$</buildArg>
                                  <buildArg>-H:IncludeResources=.*png$</buildArg>


                                  <buildArg>-H:IncludeResourceBundles=com.sun.javafx.tk.quantum.QuantumMessagesBundle
                                  </buildArg>



                              </buildArgs>
                          </configuration>
                          <executions>
                              <execution>
                                  <goals>
                                      <goal>build</goal>
                                  </goals>
                                  <phase>package</phase>
                              </execution>
                          </executions>
                      </plugin>
  -->

                    <!--                    <plugin>
                                            <groupId>org.codehaus.mojo</groupId>
                                            <artifactId>exec-maven-plugin</artifactId>
                                            <version>3.1.0</version>
                                            <executions>
                                                <execution>
                                                    <id>set-exe-icon</id>
                                                    <phase>package</phase>
                                                    <goals>
                                                        <goal>exec</goal>
                                                    </goals>
                                                    <configuration>
                                                        <executable>rcedit</executable>
                                                        <arguments>
                                                            <argument>${project.build.directory}/application.exe</argument>
                                                            <argument>&#45;&#45;set-icon</argument>
                                                            <argument>
                                                                ${project.basedir}/src/main/resources/icon/tropical_vacation_iconset.png
                                                            </argument>
                                                        </arguments>
                                                    </configuration>
                                                </execution>
                                            </executions>
                                        </plugin>-->

                </plugins>

            </build>
        </profile>

    </profiles>


    <repositories>

        <repository>
            <id>Gluon</id>
            <url>https://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
        </repository>

        <repository>
            <id>maven</id>
            <name>Maven-Central-Repository</name>
            <url>https://mvnrepository.com/artifact</url>
        </repository>

        <repository>
            <id>central</id>
            <name>Maven Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>

        <repository>
            <id>openjfx</id>
            <url>https://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
        </repository>
    </repositories>

</project>